### ISSUE TITLE
what version of lld/clang are you using?

### ISSUE THREAD

**Issue by mwotton** [nh2/link-with-lld-example#1]
when i try, i get this:

```
<no location info>: error:
    Warning: Couldn't figure out linker information!
             Make sure you're using GNU ld, GNU gold or the built in OS X linker, etc.
clang: error: unknown argument: '-no-pie'
clang: error: invalid linker name in argument '-fuse-ld=lld'
`clang' failed in phase `Linker'. (Exit code: 1)

--  While building package poker-0.1 using:
      /home/mark/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build exe:poker --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

building just an executable. entirely possible i just have the wrong set of clang/lld of course.

**Comment by nh2** [comment]
Yes, your clang is too old. Clang supports `-fuse-ld` [since 2014](https://github.com/llvm-mirror/clang/commit/bab68c96f15867af6938d9c8f922d59d31351cad). (See also [here](https://ghc.haskell.org/trac/ghc/ticket/13541#comment:10).)

**Comment by nh2** [comment]
I did the experiment with Clang 3.9 (on Ubuntu) and 4.0 (on NixOS). Even my clang-3.6 seems to not complain about `-fuse-ld`.

None of my clangs like `-no-pie`. Does that appear when simply building my example? What OS are you on?

**Comment by mwotton** [comment]
orb ➜  ~  clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Unsure about -no-pie. Trying with clang 5.

**Comment by nh2** [comment]
Sorry, I read your log incorrectly.

> clang: error: invalid linker name in argument '-fuse-ld=lld'

It's not complaining about the nonexistence of `-fuse-ld`, but about the fact of using `lld` with it.

Nevertheless, even `clang-3.6 -fuse-ld=lld` doesn't complain, neither does 3.8 (I have the exact same version output as you have).

**Comment by mwotton** [comment]
i worked it out - my ghc settings file had this line in it:

 ("C compiler supports -no-pie", "YES"),


which I think I'd changed because of this:

https://github.com/commercialhaskell/stack/issues/2712

Anyway, thanks, seems to be working now.

**Comment by nh2** [comment]
Good to know!

**Comment by sylvestre** [comment]
no-pie has been introduced here: https://reviews.llvm.org/rL308268 
and will ship in clang 5
